/* Bardly corpus.
 *
 * Shakespeare is public domain; the text is embedded directly.
 * Each entry is 4-12 words so the resulting slug stays readable.
 * Citations use the traditional act.scene form (Sonnets cite the number).
 *
 * Exposed as a plain global so this file can be loaded with a bare <script>
 * tag on GitHub Pages -- no modules, no bundler, no build step.
 */
var QUOTES = [
  /* ---- Hamlet ---- */
  { text: "To be, or not to be, that is the question", source: "Hamlet, III.i" },
  { text: "Neither a borrower nor a lender be", source: "Hamlet, I.iii" },
  { text: "This above all, to thine own self be true", source: "Hamlet, I.iii" },
  { text: "Brevity is the soul of wit", source: "Hamlet, II.ii" },
  { text: "There is nothing either good or bad but thinking makes it so", source: "Hamlet, II.ii" },
  { text: "Though this be madness, yet there is method in it", source: "Hamlet, II.ii" },
  { text: "The lady doth protest too much, methinks", source: "Hamlet, III.ii" },
  { text: "Something is rotten in the state of Denmark", source: "Hamlet, I.iv" },
  { text: "Frailty, thy name is woman", source: "Hamlet, I.ii" },
  { text: "The play is the thing", source: "Hamlet, II.ii" },
  { text: "Alas, poor Yorick, I knew him, Horatio", source: "Hamlet, V.i" },
  { text: "What a piece of work is a man", source: "Hamlet, II.ii" },
  { text: "Sweets to the sweet, farewell", source: "Hamlet, V.i" },
  { text: "Get thee to a nunnery", source: "Hamlet, III.i" },
  { text: "The rest is silence", source: "Hamlet, V.ii" },
  { text: "More matter with less art", source: "Hamlet, II.ii" },
  { text: "When sorrows come, they come not single spies", source: "Hamlet, IV.v" },
  { text: "There is a divinity that shapes our ends", source: "Hamlet, V.ii" },
  { text: "The readiness is all", source: "Hamlet, V.ii" },
  { text: "Give me that man that is not passion's slave", source: "Hamlet, III.ii" },
  { text: "I must be cruel only to be kind", source: "Hamlet, III.iv" },
  { text: "What a rogue and peasant slave am I", source: "Hamlet, II.ii" },
  { text: "How weary, stale, flat and unprofitable", source: "Hamlet, I.ii" },
  { text: "One may smile, and smile, and be a villain", source: "Hamlet, I.v" },
  { text: "There are more things in heaven and earth", source: "Hamlet, I.v" },
  { text: "Doubt thou the stars are fire", source: "Hamlet, II.ii" },
  { text: "This is the very ecstasy of love", source: "Hamlet, II.i" },
  { text: "Rich gifts wax poor when givers prove unkind", source: "Hamlet, III.i" },
  { text: "Conscience does make cowards of us all", source: "Hamlet, III.i" },
  { text: "The undiscovered country from whose bourn no traveller returns", source: "Hamlet, III.i" },
  { text: "Suit the action to the word", source: "Hamlet, III.ii" },
  { text: "A little more than kin, and less than kind", source: "Hamlet, I.ii" },
  { text: "The native hue of resolution", source: "Hamlet, III.i" },
  { text: "Diseases desperate grown by desperate appliance are relieved", source: "Hamlet, IV.iii" },

  /* ---- Macbeth ---- */
  { text: "Fair is foul, and foul is fair", source: "Macbeth, I.i" },
  { text: "Something wicked this way comes", source: "Macbeth, IV.i" },
  { text: "Out, damned spot, out, I say", source: "Macbeth, V.i" },
  { text: "Tomorrow, and tomorrow, and tomorrow", source: "Macbeth, V.v" },
  { text: "Life is but a walking shadow, a poor player", source: "Macbeth, V.v" },
  { text: "It is a tale told by an idiot", source: "Macbeth, V.v" },
  { text: "Double, double toil and trouble", source: "Macbeth, IV.i" },
  { text: "Is this a dagger which I see before me", source: "Macbeth, II.i" },
  { text: "Screw your courage to the sticking place", source: "Macbeth, I.vii" },
  { text: "Look like the innocent flower, but be the serpent", source: "Macbeth, I.v" },
  { text: "Yet do I fear thy nature", source: "Macbeth, I.v" },
  { text: "Nothing in his life became him like the leaving it", source: "Macbeth, I.iv" },
  { text: "The milk of human kindness", source: "Macbeth, I.v" },
  { text: "Sleep no more, Macbeth does murder sleep", source: "Macbeth, II.ii" },
  { text: "What is done is done", source: "Macbeth, III.ii" },
  { text: "Stars, hide your fires", source: "Macbeth, I.iv" },
  { text: "Full of scorpions is my mind, dear wife", source: "Macbeth, III.ii" },
  { text: "By the pricking of my thumbs", source: "Macbeth, IV.i" },
  { text: "Blood will have blood", source: "Macbeth, III.iv" },
  { text: "Out, out, brief candle", source: "Macbeth, V.v" },
  { text: "Vaulting ambition, which overleaps itself", source: "Macbeth, I.vii" },
  { text: "So foul and fair a day I have not seen", source: "Macbeth, I.iii" },
  { text: "Come, you spirits that tend on mortal thoughts", source: "Macbeth, I.v" },
  { text: "I have supped full with horrors", source: "Macbeth, V.v" },
  { text: "The wine of life is drawn", source: "Macbeth, II.iii" },
  { text: "Nought had, all spent, where our desire is got", source: "Macbeth, III.ii" },

  /* ---- Romeo and Juliet ---- */
  { text: "But soft, what light through yonder window breaks", source: "Romeo and Juliet, II.ii" },
  { text: "Romeo, Romeo, wherefore art thou Romeo", source: "Romeo and Juliet, II.ii" },
  { text: "That which we call a rose by any other name", source: "Romeo and Juliet, II.ii" },
  { text: "Parting is such sweet sorrow", source: "Romeo and Juliet, II.ii" },
  { text: "A plague on both your houses", source: "Romeo and Juliet, III.i" },
  { text: "For never was a story of more woe", source: "Romeo and Juliet, V.iii" },
  { text: "These violent delights have violent ends", source: "Romeo and Juliet, II.vi" },
  { text: "My only love sprung from my only hate", source: "Romeo and Juliet, I.v" },
  { text: "A pair of star-crossed lovers take their life", source: "Romeo and Juliet, Prologue" },
  { text: "Wisely and slow, they stumble that run fast", source: "Romeo and Juliet, II.iii" },
  { text: "Did my heart love till now", source: "Romeo and Juliet, I.v" },
  { text: "I am fortune's fool", source: "Romeo and Juliet, III.i" },
  { text: "Tempt not a desperate man", source: "Romeo and Juliet, V.iii" },
  { text: "He jests at scars that never felt a wound", source: "Romeo and Juliet, II.ii" },
  { text: "Thus with a kiss I die", source: "Romeo and Juliet, V.iii" },
  { text: "Love is a smoke made with the fume of sighs", source: "Romeo and Juliet, I.i" },
  { text: "Where civil blood makes civil hands unclean", source: "Romeo and Juliet, Prologue" },

  /* ---- Julius Caesar ---- */
  { text: "Friends, Romans, countrymen, lend me your ears", source: "Julius Caesar, III.ii" },
  { text: "Et tu, Brute? Then fall, Caesar", source: "Julius Caesar, III.i" },
  { text: "Beware the ides of March", source: "Julius Caesar, I.ii" },
  { text: "The fault is not in our stars but ourselves", source: "Julius Caesar, I.ii" },
  { text: "Cowards die many times before their deaths", source: "Julius Caesar, II.ii" },
  { text: "Cry havoc, and let slip the dogs of war", source: "Julius Caesar, III.i" },
  { text: "This was the noblest Roman of them all", source: "Julius Caesar, V.v" },
  { text: "Yond Cassius has a lean and hungry look", source: "Julius Caesar, I.ii" },
  { text: "Not that I loved Caesar less, but Rome more", source: "Julius Caesar, III.ii" },
  { text: "The evil that men do lives after them", source: "Julius Caesar, III.ii" },
  { text: "There is a tide in the affairs of men", source: "Julius Caesar, IV.iii" },
  { text: "Pardon me, thou bleeding piece of earth", source: "Julius Caesar, III.i" },
  { text: "The valiant never taste of death but once", source: "Julius Caesar, II.ii" },
  { text: "But I am constant as the northern star", source: "Julius Caesar, III.i" },

  /* ---- King Lear ---- */
  { text: "Nothing will come of nothing", source: "King Lear, I.i" },
  { text: "How sharper than a serpent's tooth it is", source: "King Lear, I.iv" },
  { text: "I am a man more sinned against than sinning", source: "King Lear, III.ii" },
  { text: "As flies to wanton boys are we to the gods", source: "King Lear, IV.i" },
  { text: "Blow, winds, and crack your cheeks", source: "King Lear, III.ii" },
  { text: "The wheel is come full circle", source: "King Lear, V.iii" },
  { text: "That way madness lies", source: "King Lear, III.iv" },
  { text: "Men must endure their going hence", source: "King Lear, V.ii" },
  { text: "Thou art the thing itself, unaccommodated man", source: "King Lear, III.iv" },
  { text: "Love, and be silent", source: "King Lear, I.i" },
  { text: "Have more than thou showest, speak less than thou knowest", source: "King Lear, I.iv" },

  /* ---- Othello ---- */
  { text: "Beware, my lord, of jealousy", source: "Othello, III.iii" },
  { text: "The green-eyed monster which doth mock the meat", source: "Othello, III.iii" },
  { text: "I will wear my heart upon my sleeve", source: "Othello, I.i" },
  { text: "Put money in thy purse", source: "Othello, I.iii" },
  { text: "Reputation, reputation, reputation, I have lost my reputation", source: "Othello, II.iii" },
  { text: "Who steals my purse steals trash", source: "Othello, III.iii" },
  { text: "She loved me for the dangers I had passed", source: "Othello, I.iii" },
  { text: "Speak of me as I am, nothing extenuate", source: "Othello, V.ii" },
  { text: "One that loved not wisely but too well", source: "Othello, V.ii" },
  { text: "Trifles light as air are to the jealous", source: "Othello, III.iii" },
  { text: "I am not what I am", source: "Othello, I.i" },

  /* ---- The Tempest ---- */
  { text: "We are such stuff as dreams are made on", source: "The Tempest, IV.i" },
  { text: "O brave new world that has such people in it", source: "The Tempest, V.i" },
  { text: "Hell is empty and all the devils are here", source: "The Tempest, I.ii" },
  { text: "Full fathom five thy father lies", source: "The Tempest, I.ii" },
  { text: "Misery acquaints a man with strange bedfellows", source: "The Tempest, II.ii" },
  { text: "The isle is full of noises", source: "The Tempest, III.ii" },
  { text: "What is past is prologue", source: "The Tempest, II.i" },
  { text: "Our revels now are ended", source: "The Tempest, IV.i" },
  { text: "This thing of darkness I acknowledge mine", source: "The Tempest, V.i" },

  /* ---- A Midsummer Night's Dream ---- */
  { text: "The course of true love never did run smooth", source: "A Midsummer Night's Dream, I.i" },
  { text: "Lord, what fools these mortals be", source: "A Midsummer Night's Dream, III.ii" },
  { text: "Love looks not with the eyes but with the mind", source: "A Midsummer Night's Dream, I.i" },
  { text: "Though she be but little, she is fierce", source: "A Midsummer Night's Dream, III.ii" },
  { text: "I know a bank where the wild thyme blows", source: "A Midsummer Night's Dream, II.i" },
  { text: "My Oberon, what visions have I seen", source: "A Midsummer Night's Dream, IV.i" },
  { text: "If we shadows have offended, think but this", source: "A Midsummer Night's Dream, V.i" },

  /* ---- Twelfth Night ---- */
  { text: "If music be the food of love, play on", source: "Twelfth Night, I.i" },
  { text: "Some are born great, some achieve greatness", source: "Twelfth Night, II.v" },
  { text: "Better a witty fool than a foolish wit", source: "Twelfth Night, I.v" },
  { text: "Love sought is good, but given unsought is better", source: "Twelfth Night, III.i" },
  { text: "Journeys end in lovers meeting", source: "Twelfth Night, II.iii" },
  { text: "Youth is a stuff will not endure", source: "Twelfth Night, II.iii" },
  { text: "I am all the daughters of my father's house", source: "Twelfth Night, II.iv" },
  { text: "Many a good hanging prevents a bad marriage", source: "Twelfth Night, I.v" },
  { text: "She never told her love", source: "Twelfth Night, II.iv" },

  /* ---- As You Like It ---- */
  { text: "All the world is a stage", source: "As You Like It, II.vii" },
  { text: "And all the men and women merely players", source: "As You Like It, II.vii" },
  { text: "The fool doth think he is wise", source: "As You Like It, V.i" },
  { text: "Blow, blow, thou winter wind", source: "As You Like It, II.vii" },
  { text: "Can one desire too much of a good thing", source: "As You Like It, IV.i" },
  { text: "True is it that we have seen better days", source: "As You Like It, II.vii" },
  { text: "Sweet are the uses of adversity", source: "As You Like It, II.i" },
  { text: "Men have died from time to time", source: "As You Like It, IV.i" },
  { text: "I like this place and willingly could waste my time", source: "As You Like It, II.iv" },

  /* ---- The Merchant of Venice ---- */
  { text: "All that glisters is not gold", source: "The Merchant of Venice, II.vii" },
  { text: "The quality of mercy is not strained", source: "The Merchant of Venice, IV.i" },
  { text: "If you prick us, do we not bleed", source: "The Merchant of Venice, III.i" },
  { text: "Hath not a Jew eyes", source: "The Merchant of Venice, III.i" },
  { text: "Love is blind, and lovers cannot see", source: "The Merchant of Venice, II.vi" },
  { text: "How far that little candle throws his beams", source: "The Merchant of Venice, V.i" },
  { text: "The man that hath no music in himself", source: "The Merchant of Venice, V.i" },
  { text: "It droppeth as the gentle rain from heaven", source: "The Merchant of Venice, IV.i" },

  /* ---- Much Ado About Nothing ---- */
  { text: "Sigh no more, ladies, sigh no more", source: "Much Ado About Nothing, II.iii" },
  { text: "I do love nothing in the world so well as you", source: "Much Ado About Nothing, IV.i" },
  { text: "Everyone can master a grief but he that has it", source: "Much Ado About Nothing, III.ii" },
  { text: "Speak low if you speak love", source: "Much Ado About Nothing, II.i" },
  { text: "There was never yet philosopher that could endure the toothache", source: "Much Ado About Nothing, V.i" },
  { text: "Friendship is constant in all other things", source: "Much Ado About Nothing, II.i" },

  /* ---- Histories ---- */
  { text: "Once more unto the breach, dear friends, once more", source: "Henry V, III.i" },
  { text: "We few, we happy few, we band of brothers", source: "Henry V, IV.iii" },
  { text: "Cry God for Harry, England, and Saint George", source: "Henry V, III.i" },
  { text: "I see you stand like greyhounds in the slips", source: "Henry V, III.i" },
  { text: "Men of few words are the best men", source: "Henry V, III.ii" },
  { text: "All things are ready if our minds be so", source: "Henry V, IV.iii" },
  { text: "The better part of valour is discretion", source: "Henry IV, Part 1, V.iv" },
  { text: "I can call spirits from the vasty deep", source: "Henry IV, Part 1, III.i" },
  { text: "Banish plump Jack, and banish all the world", source: "Henry IV, Part 1, II.iv" },
  { text: "Out of this nettle, danger, we pluck this flower, safety", source: "Henry IV, Part 1, II.iii" },
  { text: "Uneasy lies the head that wears a crown", source: "Henry IV, Part 2, III.i" },
  { text: "He hath eaten me out of house and home", source: "Henry IV, Part 2, II.i" },
  { text: "The first thing we do, let us kill all the lawyers", source: "Henry VI, Part 2, IV.ii" },
  { text: "A tiger's heart wrapped in a woman's hide", source: "Henry VI, Part 3, I.iv" },
  { text: "Now is the winter of our discontent", source: "Richard III, I.i" },
  { text: "A horse, a horse, my kingdom for a horse", source: "Richard III, V.iv" },
  { text: "Conscience is but a word that cowards use", source: "Richard III, V.iii" },
  { text: "So wise so young, they say, do never live long", source: "Richard III, III.i" },
  { text: "This royal throne of kings, this sceptred isle", source: "Richard II, II.i" },
  { text: "This blessed plot, this earth, this realm, this England", source: "Richard II, II.i" },
  { text: "Let us talk of graves, of worms, and epitaphs", source: "Richard II, III.ii" },
  { text: "I wasted time, and now doth time waste me", source: "Richard II, V.v" },
  { text: "Farewell, a long farewell, to all my greatness", source: "Henry VIII, III.ii" },

  /* ---- Other plays ---- */
  { text: "Age cannot wither her, nor custom stale", source: "Antony and Cleopatra, II.ii" },
  { text: "My salad days, when I was green in judgment", source: "Antony and Cleopatra, I.v" },
  { text: "I am dying, Egypt, dying", source: "Antony and Cleopatra, IV.xv" },
  { text: "Give me my robe, put on my crown", source: "Antony and Cleopatra, V.ii" },
  { text: "There is a world elsewhere", source: "Coriolanus, III.iii" },
  { text: "Some rise by sin, and some by virtue fall", source: "Measure for Measure, II.i" },
  { text: "The miserable have no other medicine but hope", source: "Measure for Measure, III.i" },
  { text: "Our doubts are traitors", source: "Measure for Measure, I.iv" },
  { text: "All is well that ends well", source: "All's Well That Ends Well, IV.iv" },
  { text: "Love all, trust a few, do wrong to none", source: "All's Well That Ends Well, I.i" },
  { text: "Exit, pursued by a bear", source: "The Winter's Tale, III.iii" },
  { text: "A sad tale is best for winter", source: "The Winter's Tale, II.i" },
  { text: "There is small choice in rotten apples", source: "The Taming of the Shrew, I.i" },
  { text: "Kiss me, Kate, we will be married on Sunday", source: "The Taming of the Shrew, II.i" },
  { text: "Why, then the world is mine oyster", source: "The Merry Wives of Windsor, II.ii" },
  { text: "This is the short and the long of it", source: "The Merry Wives of Windsor, II.ii" },
  { text: "Every why hath a wherefore", source: "The Comedy of Errors, II.ii" },
  { text: "We have seen better days", source: "Timon of Athens, IV.ii" },
  { text: "If one good deed in all my life I did", source: "Titus Andronicus, V.iii" },
  { text: "A jest's prosperity lies in the ear", source: "Love's Labour's Lost, V.ii" },
  { text: "Fear no more the heat of the sun", source: "Cymbeline, IV.ii" },
  { text: "Golden lads and girls all must come to dust", source: "Cymbeline, IV.ii" },

  /* ---- Sonnets ---- */
  { text: "Shall I compare thee to a summer's day", source: "Sonnet 18" },
  { text: "Rough winds do shake the darling buds of May", source: "Sonnet 18" },
  { text: "But thy eternal summer shall not fade", source: "Sonnet 18" },
  { text: "So long lives this, and this gives life to thee", source: "Sonnet 18" },
  { text: "Let me not to the marriage of true minds", source: "Sonnet 116" },
  { text: "Love is not love which alters when it alteration finds", source: "Sonnet 116" },
  { text: "It is the star to every wandering bark", source: "Sonnet 116" },
  { text: "Love is not Time's fool, though rosy lips and cheeks", source: "Sonnet 116" },
  { text: "My mistress' eyes are nothing like the sun", source: "Sonnet 130" },
  { text: "And yet, by heaven, I think my love as rare", source: "Sonnet 130" },
  { text: "When in disgrace with fortune and men's eyes", source: "Sonnet 29" },
  { text: "Haply I think on thee, and then my state", source: "Sonnet 29" },
  { text: "When to the sessions of sweet silent thought", source: "Sonnet 30" },
  { text: "I summon up remembrance of things past", source: "Sonnet 30" },
  { text: "Not marble, nor the gilded monuments of princes", source: "Sonnet 55" },
  { text: "Like as the waves make towards the pebbled shore", source: "Sonnet 60" },
  { text: "That time of year thou mayst in me behold", source: "Sonnet 73" },
  { text: "Bare ruined choirs, where late the sweet birds sang", source: "Sonnet 73" },
  { text: "Farewell, thou art too dear for my possessing", source: "Sonnet 87" },
  { text: "Then hate me when thou wilt, if ever, now", source: "Sonnet 90" },
  { text: "The expense of spirit in a waste of shame", source: "Sonnet 129" },
  { text: "Devouring Time, blunt thou the lion's paws", source: "Sonnet 19" },
  { text: "From fairest creatures we desire increase", source: "Sonnet 1" },
  { text: "When forty winters shall besiege thy brow", source: "Sonnet 2" },
  { text: "Poor soul, the centre of my sinful earth", source: "Sonnet 146" },
  { text: "Two loves I have, of comfort and despair", source: "Sonnet 144" },
  { text: "My love is as a fever, longing still", source: "Sonnet 147" },
  { text: "Mine eye and heart are at a mortal war", source: "Sonnet 46" },
  { text: "How like a winter hath my absence been", source: "Sonnet 97" },
  { text: "Music to hear, why hear'st thou music sadly", source: "Sonnet 8" },
  { text: "So are you to my thoughts as food to life", source: "Sonnet 75" },
  { text: "No longer mourn for me when I am dead", source: "Sonnet 71" },
  { text: "They that have power to hurt and will do none", source: "Sonnet 94" },
  { text: "Lilies that fester smell far worse than weeds", source: "Sonnet 94" },
  { text: "When I do count the clock that tells the time", source: "Sonnet 12" },
  { text: "Tired with all these, for restful death I cry", source: "Sonnet 66" },
  { text: "Since brass, nor stone, nor earth, nor boundless sea", source: "Sonnet 65" },
  { text: "Let me confess that we two must be twain", source: "Sonnet 36" },
  { text: "Being your slave, what should I do but tend", source: "Sonnet 57" },
  { text: "O, never say that I was false of heart", source: "Sonnet 109" },
  { text: "In the old age black was not counted fair", source: "Sonnet 127" },
  { text: "How oft, when thou, my music, music play'st", source: "Sonnet 128" },
  { text: "When my love swears that she is made of truth", source: "Sonnet 138" },
  { text: "Alas, it is true I have gone here and there", source: "Sonnet 110" },
  { text: "Let those who are in favour with their stars", source: "Sonnet 25" },
  { text: "Weary with toil, I haste me to my bed", source: "Sonnet 27" },
  { text: "Full many a glorious morning have I seen", source: "Sonnet 33" },
  { text: "No more be grieved at that which thou hast done", source: "Sonnet 35" },
  { text: "Against my love shall be as I am now", source: "Sonnet 63" },
  { text: "That thou hast her, it is not all my grief", source: "Sonnet 42" },
  { text: "Sweet love, renew thy force", source: "Sonnet 56" },
  { text: "How much more doth beauty beauteous seem", source: "Sonnet 54" },
  { text: "Not mine own fears, nor the prophetic soul", source: "Sonnet 107" },
  { text: "The little Love-god lying once asleep", source: "Sonnet 154" },
  { text: "Love is too young to know what conscience is", source: "Sonnet 151" }
];

/* Canonical slugifier. It lives here, next to the corpus, because the generator
 * and the resolver must agree on it exactly -- if the two ever drifted apart,
 * generated links would stop matching their own quotes.
 *
 * lowercase -> strip accents -> drop everything but a-z0-9 -> collapse to hyphens.
 * Apostrophes are removed rather than hyphenated, so "world's" -> "worlds".
 */
function slugify(text) {
  return String(text)
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")   // strip combining accents
    .replace(/[‘’']/g, "")   // apostrophes vanish, no hyphen
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")       // everything else becomes a separator
    .replace(/^-+|-+$/g, "");          // trim leading/trailing hyphens
}
